[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
via_ir = true
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 1_000_000
fs_permissions = [
  { access = "readwrite", path = "./addresses" },
  { access = "readwrite", path = "./script/config" },
  { access = "read", path = "./package.json" },
]

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 73571, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }