[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
via_ir = true
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 1_000_000
fs_permissions = [
  { access = "readwrite", path = "./addresses" },
  { access = "readwrite", path = "./script/config" },
  { access = "read", path = "./package.json" },
]

[rpc_endpoints]
base = "https://base.gateway.tenderly.co/${TENDERLY_KEY}"