[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
via_ir = true
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 1_000_000
fs_permissions = [
  { access = "readwrite", path = "./addresses" },
  { access = "read", path = "./package.json" },
]

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"