on:
  push:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Run Forge coverage
        run: forge coverage --report lcov
        env:
          TENDERLY_KEY: ${{ secrets.TENDERLY_KEY }}

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Filter files to ignore
        run: |
          lcov --rc lcov_branch_coverage=1 \
          --remove lcov.info \
          --ignore-errors unused \
          --output-file lcov.info "*test*" "script/*" "src/deployment*"

      - name: Report code coverage
        uses: iainnash/github-actions-report-lcov@v12
        with:
          output-html: false
          coverage-files: ./lcov.info
          minimum-coverage: 87
          github-token: ${{ secrets.GITHUB_TOKEN }}
