on:
  push:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set initial test status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Test status

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Build contracts
        run: |
          forge build

      - name: Test
        run: |
          forge test
        env:
          TENDERLY_KEY: ${{ secrets.TENDERLY_KEY }}

      - name: Set initial test status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Test status
